In [5]:
l = [20, 30, 10, 40]
print(l[1:3])
print(l[::2])

[30, 10]
[20, 10]


In [6]:
import numpy as np

a = np.array(l)
a

array([20, 30, 10, 40])

In [12]:
print(a[1:])
print(a[::3])

[30 10 40]
[20 40]


In [14]:
l2 = l[:]
l2

[20, 30, 10, 40]

In [15]:
l2[0] = 1000
print(l2)
print(l)

[1000, 30, 10, 40]
[20, 30, 10, 40]


In [16]:
b = a[:]
b

array([20, 30, 10, 40])

In [17]:
b[0] = 1000
print(a)
print(b)

[1000   30   10   40]
[1000   30   10   40]


In [19]:
c = a.copy()
print(c)
print(a)

[1000   30   10   40]
[1000   30   10   40]


In [20]:
c[0] = 123123
print(c)
print(a)

[123123     30     10     40]
[1000   30   10   40]
